name: Deploy React App to GitHub Pages

on:
  workflow_dispatch:  # manually trigger from GitHub UI or API
  push:
    branches:
      - gh-pages       # only run when gh-pages branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: |
          CI=false npm run build

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy build folder to gh-pages 🚀
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          npx gh-pages -d build \
            --repo https://x-access-token:${GH_PAT}@github.com/jaganathpanda/rmm.git \
            --branch gh-pages
